apply plugin: 'com.android.application'

def appProperties = new Properties()
def appPropertiesFile = rootProject.file("app/app.properties")

if (appPropertiesFile.exists()) {
    appProperties.load(new FileInputStream(appPropertiesFile))
}

android {
    namespace 'com.diasjoao.bolanatv'
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        applicationId "com.diasjoao.bolanatv"
        compileSdk 35
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 4
        versionName "4.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        manifestPlaceholders = [ads_application_id: appProperties['ads_application_id']]

        buildConfigField "String", "API_URL", "\"${appProperties['api_url_bola_na_tv']}\""
        buildConfigField "String", "ADMOB_BANNER_MAIN", "\"${appProperties['admob_banner_main']}\""
        buildConfigField "String", "ADMOB_BANNER_DETAILS", "\"${appProperties['admob_banner_details']}\""
        buildConfigField "String", "ADMOB_BANNER_PRIVACY", "\"${appProperties['admob_banner_privacy']}\""
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.navigation:navigation-fragment:2.9.7'
    implementation 'androidx.navigation:navigation-ui:2.9.7'
    implementation 'androidx.preference:preference:1.2.1'

    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.github.shuhart:stickyheader:1.1.0'
    implementation 'com.google.android.gms:play-services-ads:25.1.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'

    implementation 'org.jsoup:jsoup:1.22.1'

    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    testImplementation 'junit:junit:4.13.2'
}
