apply plugin: 'com.android.application'

def appPropertiesFile = rootProject.file("app/src/main/assets/app.properties")
def appProperties = new Properties()
appProperties.load(new FileInputStream(appPropertiesFile))

android {
    namespace 'com.diasjoao.bolanatv'
    defaultConfig {
        applicationId "com.diasjoao.bolanatv"
        compileSdkVersion 37
        minSdkVersion 26
        targetSdkVersion 37
        versionCode 5
        versionName "4.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        manifestPlaceholders = [ads_application_id: appProperties['ads_application_id']]

        resValue("string", "admob_banner_details", appProperties['admob_banner_details'])
        resValue("string", "admob_banner_main", appProperties['admob_banner_main'])
        resValue("string", "admob_banner_privacy", appProperties['admob_banner_privacy'])
        resValue("string", "api_url_bola_na_tv", appProperties['api_url_bola_na_tv'])
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.navigation:navigation-fragment:2.10.2'
    implementation 'androidx.navigation:navigation-ui:2.10.2'
    implementation 'androidx.preference:preference:1.2.1'

    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.github.shuhart:stickyheader:1.1.0'
    implementation 'com.google.android.gms:play-services-ads:25.5.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.squareup.okhttp3:okhttp:5.5.0'

    implementation 'org.jsoup:jsoup:1.23.2'

    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    testImplementation 'junit:junit:4.13.2'
}
